### ISSUE TITLE
More python errors

### ISSUE THREAD

**Issue by cuvtixo** [Thenujan-0/grub-editor#12]
Traceback (most recent call last):
  File "/opt/grub-editor/grubEditor/libs/worker.py", line 84, in run
    self.signals.result.emit(result)  # Return the result of the processing
    ^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type WorkerSignals has been deleted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/grub-editor/grubEditor/libs/worker.py", line 86, in run
    self.signals.finished.emit()  # Done
    ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type WorkerSignals has been deleted

EndeavourOS  64_86x

**Comment by YutharsanS** [comment]
Thank you for being interested in this project ❤️ 
Unfortunately, the project is no longer maintained.
