### ISSUE TITLE
ValueError: could not convert string to float: -1

### ISSUE THREAD

**Issue by opok** [Thenujan-0/grub-editor#6]
After booting into Kubuntu live to move root partition and saving grub configuration from grub-customizer (available in kubuntu) I am getting this error when I try to start grub-editor 1.11-1 in Manjaro:

```
Traceback (most recent call last):
  File "/opt/grub-editor/__main__.py", line 66, in <module>
    main_()
  File "/opt/grub-editor/__main__.py", line 56, in main_
    main.main()
  File "/opt/grub-editor/main.py", line 2018, in main
    MainWindow=Ui()
  File "/opt/grub-editor/main.py", line 546, in __init__
    self.setUiElements(show_issues=True)
  File "/opt/grub-editor/main.py", line 965, in setUiElements
    if float(timeout)==0:
ValueError: could not convert string to float: -1
```

Do you need anything else ? like some grub config or something else that might be causing this ?

**Comment by Thenujan-0** [comment]
Yes please provide the contents of /etc/default/grub

**Comment by Thenujan-0** [comment]
The issue is reproducible when using double quotes around the value of GRUB_TIMEOUT. Thank you for reporting the issue I will look into it.
