### ISSUE TITLE
Grub Editor not launching - Manjaro GNOME

### ISSUE THREAD

**Issue by MeHashOnHold** [Thenujan-0/grub-editor#7]
Traceback (most recent call last):
  File "/opt/grub-editor/__main__.py", line 66, in <module>
    main_()
  File "/opt/grub-editor/__main__.py", line 56, in main_
    main.main()
  File "/opt/grub-editor/main.py", line 2018, in main
    MainWindow=Ui()
  File "/opt/grub-editor/main.py", line 546, in __init__
    self.setUiElements(show_issues=True)
  File "/opt/grub-editor/main.py", line 965, in setUiElements
    if float(timeout)==0:
ValueError: could not convert string to float: 10

**Comment by Thenujan-0** [comment]
The issue has already been fixed the only thing needed right now is another release.
Anyway thank you for reporting the issue

**Comment by Thenujan-0** [comment]
Another update has been released :partying_face: 
Try updating and please report if you still get the error
